In [1]:
import pandas as pd
df=pd.read_csv("https://goz39a.s3.eu-central-1.amazonaws.com/hepatitis_csv.csv")

In [2]:
df.head()

,age,sex,steroid,antivirals,fatigue,malaise,anorexia,liver_big,liver_firm,spleen_palpable,spiders,ascites,varices,bilirubin,alk_phosphate,sgot,albumin,protime,histology,class
0,30,male,False,False,False,False,False,False,False,False,False,False,False,1.0,85.0,18.0,4.0,NaN,False,live
1,50,female,False,False,True,False,False,False,False,False,False,False,False,0.9,135.0,42.0,3.5,NaN,False,live
2,78,female,True,False,True,False,False,True,False,False,False,False,False,0.7,96.0,32.0,4.0,NaN,False,live
3,31,female,NaN,True,False,False,False,True,False,False,False,False,False,0.7,46.0,52.0,4.0,80.0,False,live
4,34,female,True,False,False,False,False,True,False,False,False,False,False,1.0,NaN,200.0,4.0,NaN,False,live

In [3]:
df.shape

(155, 20)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155 entries, 0 to 154
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              155 non-null    int64
 1   sex              155 non-null    object
 2   steroid          154 non-null    object
 3   antivirals       155 non-null    bool
 4   fatigue          154 non-null    object
 5   malaise          154 non-null    object
 6   anorexia         154 non-null    object
 7   liver_big        145 non-null    object
 8   liver_firm       144 non-null    object
 9   spleen_palpable  150 non-null    object
 10  spiders          150 non-null    object
 11  ascites          150 non-null    object
 12  varices          150 non-null    object
 13  bilirubin        149 non-null    float64
 14  alk_phosphate    126 non-null    float64
 15  sgot             151 non-null    float64
 16  albumin          139 non-null    float64
 17  protime          88 non-null     float64
 18  histology        155 non-null    bool
 19  class            155 non-null    object
dtypes: bool(2), float64(5), int64(1), object(12)
memory usage: 22.2+ KB

In [5]:
df.isna().sum(axis=0)

age                 0
sex                 0
steroid             1
antivirals          0
fatigue             1
malaise             1
anorexia            1
liver_big          10
liver_firm         11
spleen_palpable     5
spiders             5
ascites             5
varices             5
bilirubin           6
alk_phosphate      29
sgot                4
albumin            16
protime            67
histology           0
class               0
dtype: int64

#### Drop the missing values
#### Replace them with a value
#### Leave it as it is

In [6]:
import numpy as np
numeric=df.select_dtypes(include=np.number)
print(numeric)
numeric_columns=numeric.columns
print(numeric_columns)

     age  bilirubin  alk_phosphate   sgot  albumin  protime
0     30        1.0           85.0   18.0      4.0      NaN
1     50        0.9          135.0   42.0      3.5      NaN
2     78        0.7           96.0   32.0      4.0      NaN
3     31        0.7           46.0   52.0      4.0     80.0
4     34        1.0            NaN  200.0      4.0      NaN
..   ...        ...            ...    ...      ...      ...
150   46        7.6            NaN  242.0      3.3     50.0
151   44        0.9          126.0  142.0      4.3      NaN
152   61        0.8           75.0   20.0      4.1      NaN
153   53        1.5           81.0   19.0      4.1     48.0
154   43        1.2          100.0   19.0      3.1     42.0

[155 rows x 6 columns]
Index(['age', 'bilirubin', 'alk_phosphate', 'sgot', 'albumin', 'protime'], dtype='object')

In [10]:
df[numeric_columns]=df[numeric_columns].fillna(df[numeric_columns].median())

In [11]:
df.isna().sum()

age                 0
sex                 0
steroid             1
antivirals          0
fatigue             1
malaise             1
anorexia            1
liver_big          10
liver_firm         11
spleen_palpable     5
spiders             5
ascites             5
varices             5
bilirubin           0
alk_phosphate       0
sgot                0
albumin             0
protime             0
histology           0
class               0
dtype: int64

In [13]:
boolean_columns=df.select_dtypes(include=object).columns.tolist()
print(boolean_columns)
boolean_columns.remove("class")
print(boolean_columns)
df[boolean_columns]=df[boolean_columns].astype("bool")

['sex', 'steroid', 'fatigue', 'malaise', 'anorexia', 'liver_big', 'liver_firm', 'spleen_palpable', 'spiders', 'ascites', 'varices', 'class']
['sex', 'steroid', 'fatigue', 'malaise', 'anorexia', 'liver_big', 'liver_firm', 'spleen_palpable', 'spiders', 'ascites', 'varices']

In [14]:
df[boolean_columns]=df[boolean_columns].fillna(df[boolean_columns].mode())

In [16]:
df.isna().sum()

age                0
sex                0
steroid            0
antivirals         0
fatigue            0
malaise            0
anorexia           0
liver_big          0
liver_firm         0
spleen_palpable    0
spiders            0
ascites            0
varices            0
bilirubin          0
alk_phosphate      0
sgot               0
albumin            0
protime            0
histology          0
class              0
dtype: int64

In [35]:
df=pd.read_csv("https://goz39a.s3.eu-central-1.amazonaws.com/sample_tweets/sample.csv")
print(df.shape)

(386, 21)

In [36]:
df.head(15)

,Tweet Id,Tweet URL,Tweet Posted Time (UTC),Tweet Content,Tweet Type,Client,Retweets Received,Likes Received,Tweet Location,Tweet Language,...,Name,Username,User Bio,Verified or Non-Verified,Profile URL,Protected or Non-protected,User Followers,User Following,User Account Creation Date,Impressions
0,"""1167429261210218497""",https://twitter.com/animalhealthEU/status/1167...,30 Aug 2019 13:30:00,Pets change our lives &amp; become a part of o...,Tweet,Twitter Ads Composer,0,4,Brussels,English,...,AnimalhealthEurope,animalhealthEU,AnimalhealthEurope represents manufacturers of...,Non-Verified,https://twitter.com/animalhealthEU,Non-Protected,3697,542,17 Dec 2012 09:14:15,7394
1,"""1167375334670557185""",https://twitter.com/PennyBrohnUK/status/116737...,30 Aug 2019 09:55:43,Another spot of our #morethanmedicine bus in #...,Tweet,Twitter Web App,0,5,"Pill, Bristol",English,...,Penny Brohn UK,PennyBrohnUK,We help people live well with the impact of ca...,Non-Verified,https://twitter.com/PennyBrohnUK,Non-Protected,3227,1571,15 Sep 2010 09:44:02,6454
2,"""1167237977615097861""",https://twitter.com/lordbyronaf/status/1167237...,30 Aug 2019 00:49:54,What a great team ⁦@HealthSourceOH⁩ ⁦@Local12⁩...,ReTweet,Twitter for Android,0,0,"Ohio, USA",English,...,Lord ByronAF,lordbyronaf,"It's easier to be who you are, than it is to b...",Non-Verified,https://twitter.com/lordbyronaf,Non-Protected,7808,8617,25 Jul 2012 15:43:47,0
3,"""1167236897078480898""",https://twitter.com/CountessDavis/status/11672...,30 Aug 2019 00:45:37,What a great team ⁦@HealthSourceOH⁩ ⁦@Local12⁩...,ReTweet,Twitter for Android,0,0,NaN,English,...,Lisa Countess davis,CountessDavis,I am named after @ElvisPresley daughter Lisa M...,Non-Verified,https://twitter.com/CountessDavis,Non-Protected,291,81,26 Jan 2017 18:21:42,0
4,"""1167228378191204353""",https://twitter.com/Local12/status/11672283781...,30 Aug 2019 00:11:46,What a great team ⁦@HealthSourceOH⁩ ⁦@Local12⁩...,ReTweet,TweetDeck,0,0,"Cincinnati, OH",English,...,Local 12/WKRC-TV,Local12,Local 12 is #Cincinnati's trusted source for b...,Verified,https://twitter.com/Local12,Non-Protected,198675,651,02 Sep 2008 20:09:44,0
5,"""1167228285463531520""",https://twitter.com/lbonis1/status/11672282854...,30 Aug 2019 00:11:23,What a great team ⁦@HealthSourceOH⁩ ⁦@Local12⁩...,Tweet,Twitter for iPhone,3,17,WKRC TV,English,...,Liz Bonis,lbonis1,Health and Medical Reporter/News Anchor Regist...,Verified,https://twitter.com/lbonis1,Non-Protected,6015,4866,16 Mar 2013 12:05:02,12033
6,"""1167163662051631104""",https://twitter.com/luapppank/status/116716366...,29 Aug 2019 19:54:36,Will you be at #FIX19? Want a preview of @AG_E...,ReTweet,Twitter for iPhone,0,0,"Scottsdale, AZ",English,...,paul knapp,luapppank,16.2 (and rising) hdcp golfer. fairways and gr...,Non-Verified,https://twitter.com/luapppank,Non-Protected,69,81,17 May 2009 12:58:43,0
7,"""1167109799282118656""",https://twitter.com/AG_EM33/status/11671097992...,29 Aug 2019 16:20:34,Will you be at #FIX19? Want a preview of @AG_E...,ReTweet,Twitter for iPhone,0,0,NaN,English,...,Alin,AG_EM33,DO &amp; MPH | EM resident | Interests: #FOAMe...,Non-Verified,https://twitter.com/AG_EM33,Non-Protected,9655,3043,26 Mar 2016 03:57:53,0
8,"""1167071808895541248""",https://twitter.com/andyglittle/status/1167071...,29 Aug 2019 13:49:37,Will you be at #FIX19? Want a preview of @AG_E...,ReTweet,Twitter for iPhone,0,0,"Columbus,OH",English,...,Andy Little,andyglittle,"EM DOC @DoctorsEMres, PodCaster, lover of my f...",Non-Verified,https://twitter.com/andyglittle,Non-Protected,1697,1123,25 Nov 2013 19:42:29,0
9,"""1167069888474537984""",https://twitter.com/MOX13/status/1167069888474...,29 Aug 2019 13:41:59,Will you be at #FIX19? Want a preview of @AG_E...,ReTweet,Twitter for iPhone,0,0,NaN,English,...,Tanner Gronowski,MOX13,"Emergency Medicine Doc, outdoor enthusiast, am...",Non-Verified,https://twitter.com/MOX13,Non-Protected,796,613,02 Jun 2009 17:50:10,0
10,"""1167062757126094848""",https://twitter.com/dkalnow/status/11670627571...,29 Aug 2019 13:13:38,Will you be at #FIX19? Want a preview of @AG_E...,ReTweet,Twitter for iPhone,0,0,"Columbus, OH",English,...,Drew Kalnow,dkalnow,EM Physician and Sim Director @DoctorsEMres Oc...,Non-Verified,https://twitter.com/dkalnow,Non-Protected,771,394,30 Mar 2014 01:06:26,0
11,"""1167061075075973123""",https://twitter.com/EMOverEasy/status/11670610...,29 Aug 2019 13:06:57,Will you be at #FIX19? Want a preview of @AG_E...,Tweet,Twitter Web App,6,19,"DK Diner, USA",English,...,EMOverEasy,EMOverEasy,Tackling real world problems from the EM persp...,Non-Verified,https://twitter.com/EMOverEasy,Non-Protected,1345,361,09 Mar 2016 15:04:58,2696
12,"""1166892836165496835""",https://twitter.com/AndreaWestbyMD/status/1166...,29 Aug 2019 01:58:26,Y’all ⁦@UMNNMFamMedRes⁩ Rose Marie Leslie is a...,Tweet,Twitter for iPhone,0,27,"Minneapolis, MN",English,...,Andrea Westby,AndreaWestbyMD,"She/her/hers. Teacher of family medicine, form...",Non-Verified,https://twitter.com/AndreaWestbyMD,Non-Protected,938,1247,15 Apr 2015 19:58:49,1876
13,"""1166860403516813318""",https://twitter.com/RealZiggyFlo/status/116686...,28 Aug 2019 23:49:34,"@Medtronic Here, here! Engage with your patien...",ReTweet,Twitter Web App,0,0,Life zig zags so go with the flow. RT not nece...,English,...,ℛεɑℓℤɩɠɠƴℱℓℴ,RealZiggyFlo,Cure Duchenne http://www.parentprojectmd.org/,Non-Verified,https://twitter.com/RealZiggyFlo,Non-Protected,628,870,11 Apr 2011 10:36:42,0
14,"""1166742759232790529""",https://twitter.com/HolmesHaddad/status/116674...,28 Aug 2019 16:02:05,"@Medtronic Here, here! Engage with your patien...",Reply,Twitter Web App,1,1,"San Francisco Bay Area, USA",English,...,Laura Holmes Haddad,HolmesHaddad,"Writer, mom, dog lover, inflammatory breast ca...",Non-Verified,https://twitter.com/HolmesHaddad,Non-Protected,355,645,20 Jul 2015 20:15:28,711

In [37]:
df.isna().sum()

Tweet Id                       0
Tweet URL                      0
Tweet Posted Time (UTC)        0
Tweet Content                  0
Tweet Type                     0
Client                         0
Retweets Received              0
Likes Received                 0
Tweet Location                61
Tweet Language                 1
User Id                        0
Name                           0
Username                       0
User Bio                      19
Verified or Non-Verified       0
Profile URL                    0
Protected or Non-protected     0
User Followers                 0
User Following                 0
User Account Creation Date     0
Impressions                    0
dtype: int64

In [38]:
df.dtypes

Tweet Id                      object
Tweet URL                     object
Tweet Posted Time (UTC)       object
Tweet Content                 object
Tweet Type                    object
Client                        object
Retweets Received              int64
Likes Received                 int64
Tweet Location                object
Tweet Language                object
User Id                       object
Name                          object
Username                      object
User Bio                      object
Verified or Non-Verified      object
Profile URL                   object
Protected or Non-protected    object
User Followers                 int64
User Following                 int64
User Account Creation Date    object
Impressions                    int64
dtype: object

In [39]:
df.describe()

,Retweets Received,Likes Received,User Followers,User Following,Impressions
count,386.000000,386.000000,386.000000,386.000000,386.000000
mean,0.730570,2.839378,2516.904145,1067.401554,1137.849741
std,1.884991,9.423381,10529.124870,1409.750825,2381.107457
min,0.000000,0.000000,0.000000,4.000000,0.000000
25%,0.000000,0.000000,348.000000,379.000000,0.000000
50%,0.000000,0.000000,796.000000,542.000000,0.000000
75%,0.000000,1.000000,2922.500000,1123.000000,882.000000
max,13.000000,98.000000,198675.000000,12476.000000,12033.000000

In [40]:
df.dropna(how="any", inplace=True)

In [41]:
df.shape

(317, 21)

In [42]:
df["Tweet Location"]=df["Tweet Location"].astype("string")

In [43]:
df.dtypes

Tweet Id                      object
Tweet URL                     object
Tweet Posted Time (UTC)       object
Tweet Content                 object
Tweet Type                    object
Client                        object
Retweets Received              int64
Likes Received                 int64
Tweet Location                string
Tweet Language                object
User Id                       object
Name                          object
Username                      object
User Bio                      object
Verified or Non-Verified      object
Profile URL                   object
Protected or Non-protected    object
User Followers                 int64
User Following                 int64
User Account Creation Date    object
Impressions                    int64
dtype: object

<StringArray>
[                                 'brussels',
                             'pill, bristol',
                                 'ohio, usa',
                            'cincinnati, oh',
                                   'wkrc tv',
                            'scottsdale, az',
                               'columbus,oh',
                              'columbus, oh',
                             'dk diner, usa',
                           'minneapolis, mn',
 ...
                           'kampala, uganda',
                        'ilorin,kwara state',
                            'nigeria, lagos',
                                    'kigali',
                        'towcester, england',
 'heart of the eu (the clue is in the name)',
                       'south west, england',
                                'manchester',
                               'seattle, wa',
                         'in my happy place']
Length: 102, dtype: string

In [52]:
import re  #regular expressions manipulates strings 
def set_pattern(x):
    pattern=r'[(A-Z)]\w+,([A-Z])\w+' #w+ means many letter preceded by a capital letter
    res=re.match(pattern, x)
    if res:
        x=x.replace(",", ", ")
    return x

In [53]:
df["Tweet Location"]=df.apply(lambda x: set_pattern(x["Tweet Location"]), axis=1) #much faster

In [54]:
df["Tweet Location"].unique()

array(['Brussels', 'Pill,  Bristol', 'Ohio,  USA', 'Cincinnati,  OH',
       'WKRC TV', 'Scottsdale,  AZ', 'Columbus, OH', 'Columbus,  OH',
       'DK Diner, USA', 'Minneapolis,  MN',
       'Life zig zags so go with the flow. RT not necessarily endorsement ❅Proud Patriotic Progressive Snowflake❅ Keep our freedom People Come First',
       'San Francisco Bay Area, USA',
       'südlich der südlichsten Stadt Deutschlands',
       'Breuberg,  Deutschland', 'Bonn,  Deutschland', 'Warszawa',
       'Connecticut', 'Manhattan,  NY', 'Bristol', 'Brussels,  Belgium',
       'Brooklyn,  NY', 'UK and Germany', 'Miami,  FL', "Côte d'Ivoire",
       'Kingdom of Saudi Arabia', 'Bath,  England', 'Paris',
       'Basel,  Switzerland', 'Warsaw,  Poland', 'Canton,  Ohio',
       'Fresno,  CA', 'California,  USA', 'New York, NY', 'Malaysia',
       'Kentucky,  USA 🇺🇸', 'Bristol,  United Kingdom', 'Warwickshire',
       'Udine,  Friuli-Venezia Giulia', 'Bristol,  England',
       'Boston,  MA', 'Central Texas', 'Europe', 'Lisbon,  Portugal',
       'España', 'lillois', 'POLAND', 'Kenya', 'Nairobi Kenya',
       'Pécs Magyarország', 'Украина', 'Nairobi,  Kenya',
       'Providencia,  Chile', 'Shropshire', 'Dublin,  Ireland',
       'New Jersey, USA', 'Hackney Wick, east London, UK',
       'Manchester,  England', 'Woodley HC Stockport', 'Madrid',
       ' NJ, USA', 'Global', 'Tongeren,  België',
       'Global headquarters, Monheim', 'Dallas,  TX', 'Columbus,  Ohio',
       'Tala', 'Kochi,  Kerala INDIA', 'Stoke-on-Trent',
       'Rural Wiltshire ', 'Washington,  DC', 'Västerås,  Sweden',
       'Scotland,  United Kingdom', 'London', 'Midlands', 'EU ',
       'Worldwide', 'Yosemite,  CA', 'England,  United Kingdom',
       'San Francisco, CA', 'Raamsdonksveer', 'Czech republic 🇨🇿',
       'Ingelheim,  Germany', 'Cleveland,  OH', 'United States',
       'Kiev and Ukraine. ************', 'Karachi / Islamabad ',
       'Harrow and Croxley Green', 'Philadelphia,  PA',
       'Hackney,  London', 'Bordeaux,  France', 'UK', 'Taiwan',
       'Kampala,  Uganda', 'ilorin,kwara state', 'Nigeria,  Lagos',
       'Kigali', 'Towcester,  England',
       'Heart of the EU (the clue is in the name)', 'South West, England',
       'Manchester', 'Seattle,  WA', 'in my happy place'], dtype=object)